### ISSUE TITLE
Cambiare nome database InfluxDB

### ISSUE THREAD

**Issue by AlbertoGobbo** [GruppOne/stalker-server#12]
Causa errore "_found -, excepted ;_" per com'è scritto il nome previsto del database "stalker-tsdb"
Propongo di passare da ~~stalker-tsdb~~ a **stalker_tsdb** 
E poi fare un refactor di massa sui file che contengono questo nome

**Comment by erclu** [comment]
in teoria basta fare escaping del nome con "stalker-tsdb"
