### ISSUE TITLE
Gestire correttamente le coordinate dei luoghi

### ISSUE THREAD

**Issue by fab-dev-20** [GruppOne/stalker-server#17]
MySQL gestisce il tipo Geometry attraverso alcuni tipi particolari, a noi ne interessano solo due:

1. _Linestring_ - "Una _Linestring_ è una curva con interpolazione lineare tra i punti."
2. _Polygon_ - "Un _Polygon_ è una superficie piana che rappresenta una geometria a più lati. È definito da un singolo confine esterno e zero o più confini interni, in cui ciascun confine interno definisce un foro nel poligono."

_Linestring_ accetta dati del tipo:
- LINESTRING(45.411561 11.887471, 45.411224 11.887326,45.411111 11.887785,45.41144 11.887939)
Semplicemente una linea di 4 punti.

_Polygon_ accetta dati del tipo:
- POLYGON((45.411561 11.887471, 45.411224 11.887326,45.411111 11.887785,45.41144 11.887939,45.411561 11.887471), 0)
In corrispondenza di ", 0" dovremmo inserire, se esistono, i suddetti _fori nel poligono_, e appunto 0 altrimenti, inoltre la **prima** e l'**ultima** coordinata **devono essere uguali**, cosa invece non richiesta in _Linestring_, a significare appunto che il poligono è in una forma geometricamente corretta "una figura geometrica piana delimitata da una linea spezzata chiusa", altrimenti MySQL segnala errore.

Prendiamo ora in esame il caso **Torre Archimede**, le sue coordinate in leaflet sono 4, corrispondenti ai 4 vertici del quadrilatero che rappresenta la forma dell'edificio Torre Archimede.
Quando disegnamo questo poligono, Leaflet ci passa questi dati:
- LatLng(45.41156, 11.887477),LatLng(45.411229, 11.887316),LatLng(45.411112, 11.887789),LatLng(45.41144, 11.887939)
Se notate, la forma è simile a quella di una linestring, ma è interpretata da Leaflet come un poligono perché gli diciamo noi di farlo.

Quindi, per il database, secondo voi cosa scegliamo?
1. Un più "logicamente" corretto _Polygon_, con tutte le complicanze che comprende (considerate per esempio che dalla web app con la POST bisognerà passare al server un json contenente le 4 coordinate + la 5ᵃ ripetendo la prima, e poi nella GET il server dovrà inviare il dato senza l'ultima coordinata, oppure la web-app dovrà "pulirlo" prima di passare il dato a Leaflet.
2. _Linestring_, che ci risolve tutto il problema, ma che ci fa perdere il concetto di "logicamente corretto" e che NON ci permetterà di memorizzare eventuali _fori nel poligono_, cosa che comunque ora non facciamo e non è prevista, ma che non potrà proprio succedere mai.

**Comment by RiccardoAgatea** [comment]
I fori del poligono sono essenzialmente buchi? See è così io direi che possiamo anche ignorare la possibilità.

Comunque, direi di usare _polygon_, per consistenza concettuale, ma far aggiungere/rimuovere il punto ripetuto alla fine dal server, nella funzione che fa la query. In questo modo il db vede un polygon come piace a lui, mentre tutto il resto del sistema vede un polygon come piace a noi.

**Comment by fab-dev-20** [comment]
> I fori del poligono sono essenzialmente buchi?

Esatto, immagina il caso Torre Archimede in cui invece del solo quadrato si veda una specie di ciambella

**Comment by erclu** [comment]
> I fori del poligono sono essenzialmente buchi? See è così io direi che possiamo anche ignorare la possibilità.

fonte diretta se vuoi leggertelo: https://dev.mysql.com/doc/refman/8.0/en/gis-class-polygon.html

sta cosa dei buchi la ignorerei alla grande, il nostro concetto di polygon è na roba potenzialmente concava ma senza buchi. Ci basiamo sul polygon di mysql senza usarne tutte le feature secondo me.

> far aggiungere/rimuovere il punto ripetuto alla fine dal server, nella funzione che fa la query. In questo modo il db vede un polygon come piace a lui, mentre tutto il resto del sistema vede un polygon come piace a noi.

io terrei come SSOT il polygon con "doppio punto" iniziale e finale di mysql, lo dichiarerei nell'api e adatterei le componenti.

perché non siamo sicuri di che datatype voglia android, e ha più senso logico "far adattare" la web app al datatype dell'api/server e la mobile app al datatype dell'api/server che non adattare il server e l'app al datatype della web app

**Comment by fab-dev-20** [comment]
Ho scritto una query (select) che potenzialemente sarebbe in grado di restituire il json come lo vogliamo noi, dato un tipo POLYGON nel db, devo testarla, ma in soldoni fa una serie di substring e concatenazioni direttamente da mysql e modifica il dato restituito ( _POLYGON((45.411561 11.887471, 45.411224 11.887326,45.411111 11.887785,45.41144 11.887939,45.411561 11.887471), 0)_ ) in una stringa nella forma di un file json

**Comment by erclu** [comment]
> restituire il json come lo vogliamo noi

cioè la query ti da un json? ma questo è un problema, non un bonus, nel senso che è compito del server sputar fuori un json all'endpoint

> fa una serie di substring e concatenazioni direttamente da mysql

non sono per niente convinto della cosa.. manipolare i json concatenando stringhe è una ricetta per il disastro.

mi puoi scrivere qui sotto la query?

**Comment by erclu** [comment]
questa è la reference per fare mapping da json al db:

https://docs.spring.io/spring-data/r2dbc/docs/1.1.0.M4/reference/html/#mapping

una soluzione alternativa potrebbe essere di abbandonare il type polygon nel db e limitarci a fare una copia in sql del formato testuale prodotto da leaflet. ovvero una tabella "GeographicalPoints" e una tabella Polygon con colonne "placeId" e "geographicalPointId"


Piccolo appunto teorico. questo è lo standard de facto su cui si basano le rappresentazioni di dati geospaziali e su cui si basa MySQL: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry
sono abbastanza sicuro che anche leaflet abbia delle opzioni per convertire i suoi polygon a WKT/WKB

**Comment by fab-dev-20** [comment]
Piano Luca, non prendere paura

Se tu fai una `SELECT id, organizationId, name, ST_AsText(position) as position FROM place WHERE id=1`  ottieni una roba tipo questa:
`[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":"POLYGON((45.408351 11.886792,45.408164 11.886736,45.408115 11.887098,45.408351 11.886792))"}] `

Con la query che ho scritto ottengo una cosa così:
`[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":[{"latitude":"45.408351","longitude":"11.886792"},{"latitude":"45.408164","longitude":"11.886736"},{"latitude":"45.408115","longitude":"11.887098"},{"latitude":"45.408351","longitude":"11.886792"}]}]`

Che non mi sembra malissimo, si tratta semplicemente di prendere `position` e al posto di quella roba metterci una stringa formattata in modo che sia riconoscibile come un json

**Comment by erclu** [comment]
> Piano Luca, non prendere paura

scusami, ho ancora una PTSD da un vecchio progetto in cui la gente produceva html concatenando stringhe da dentro il php :|

> Se tu fai una `SELECT id, organizationId, name, ST_AsText(position) as position FROM place WHERE id=1` ottieni una roba tipo questa:
> `[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":"POLYGON((45.408351 11.886792,45.408164 11.886736,45.408115 11.887098,45.408351 11.886792))"}] `
> 
> Con la query che ho scritto ottengo una cosa così:
> `[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":[{"latitude":"45.408351","longitude":"11.886792"},{"latitude":"45.408164","longitude":"11.886736"},{"latitude":"45.408115","longitude":"11.887098"},{"latitude":"45.408351","longitude":"11.886792"}]}]`
> 
> Che non mi sembra malissimo, si tratta semplicemente di prendere `position` e al posto di quella roba metterci una stringa formattata in modo che sia riconoscibile come un json

Ok però ricordati che noi non manipoliamo mai JSON nel server. il JSON è prodotto automaticamente dall'object che passiamo al controller

mettiti pure su una nuova branch a fare sti tentativi, adesso mergio le due branch su cui stavamo lavorando noi che son concluse

**Comment by fabioscettro** [comment]
Ma se io ti dico crea un json con questi dati:
1. id: 1
2. organizationId: 1
3. name: Aule Luzzati
4. position: POLYGON((45.408351 11.886792,45.408164 11.886736,45.408115 11.887098,45.408351 11.886792))

In teoria il risultato è questo:
`[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":"POLYGON((45.408351 11.886792,45.408164 11.886736,45.408115 11.887098,45.408351 11.886792))"}]`

Se invece ti passo questi:
1. id: 1
2. organizationId: 1
3. name: Aule Luzzati
4. position: [[latitude:45.408351,longitude:11.886792],[latitude:45.408164,longitude:11.886736],[latitude:45.408115,longitude:11.887098],[latitude:45.408351,longitude:11.886792]]

Allora in teoria il risultato diventa questo:
`[{"id":"1","organizationId":"1","name":"Aule Luzzati","position":"[[latitude:45.408351,longitude:11.886792],[latitude:45.408164,longitude:11.886736],[latitude:45.408115,longitude:11.887098],[latitude:45.408351,longitude:11.886792]]"}]`

No?

**Comment by erclu** [comment]
dimenticato di chiudere l'issue con la pr
