### ISSUE TITLE
Requisito duplicato -  R056F1

### ISSUE THREAD

**Issue by TobiaApolloni** [GruppOne/stalker-server#57]
R056F1: "Il server deve rifiutare la richiesta di autenticazione se i dati inseriti non rispettano i vincoli imposti, o se la combinazione di email e password non è presente nel database"

---

R016F1: "Il server deve rifiutare la richiesta di autenticazione se la combinazione di email e password non è presente nel database"

Il requisito R056F1 è di fatto una ripetizione di R016F1, con contenuto errato, in quanto il server non controlla i requisiti di password e username, ma soltanto la loro presenza.
Cosa dite che ne facciamo?

**Comment by erclu** [comment]
potremmo riformulare il 56 come "le password/email inserite nei client devono rispettare i vincoli imposti". o c'è già anche quello? più che altro se lo eliminiamo dall'AdR ci tocca cambiare tutti i numeri

**Comment by TobiaApolloni** [comment]
C'è già, sono espressi come requisiti separati nelle web app/mobile app.
Sono d'accordo che non è il caso di rimuoverlo e far casino, rifraseggiamolo per essere un "marco-punto", che ne ingloba altri (tipo, "sviluppare un server"), così si completa facendo i suoi sottopunti

**Comment by erclu** [comment]
> Sono d'accordo che non è il caso di rimuoverlo e far casino, rifraseggiamolo per essere un "marco-punto", che ne ingloba altri (tipo, "sviluppare un server"), così si completa facendo i suoi sottopunti

ottima idea! però più che inglobare "sviluppare un server", lo userei per inglobare questi:

> C'è già, sono espressi come requisiti separati nelle web app/mobile app.

**Comment by TobiaApolloni** [comment]
Eh, era esattamente quella l'idea XD
